### ISSUE TITLE
[Error] Commit limit exceeded

### ISSUE THREAD

**Issue by WeikuiWang** [FloydaGithub/fake-commit#1]
昨天今天，Windws系统上，第一次运行文件时循环出现：
[Info] find_fake_repo ... 1
……
[Info] find_fake_repo ... 9
[Info] create_fake_repo ... 1
……
[Info] create_fake_repo ... 9
[Info] Cann't get repository   最后提示[Error] Commit limit exceeded。第二次运行就提示：[Error] Cann't search User: <……>   。  用户名和密码我都有改过了，但最后好像都没有commit成功，不知这个问题有人遇到吗？
![20170421091921](https://cloud.githubusercontent.com/assets/16658472/25258694/b19cc5e6-2673-11e7-90b3-bd9abf6f43a8.jpg)

**Comment by floydawong** [comment]
因为不想把账号密码写在代码中, 所以在运行的时候, 检查有没有config文件, 如果没有就生成一个. 然而config文件我放到忽略列表里面了, 所以... 你可能要跑一次, 然后再去修改config, 然后再跑这个脚本...
